// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/thnkrn/go-gin-template/pkg/api"
	"github.com/thnkrn/go-gin-template/pkg/api/handler"
	"github.com/thnkrn/go-gin-template/pkg/repository/adapter"
	adapter2 "github.com/thnkrn/go-gin-template/pkg/usecase/adapter"
)

// Injectors from wire.go:

func InitializeAPI() (*api.ServerHTTP, error) {
	repository := adapter.NewRepo()
	usecase := adapter2.NewUseCase(repository)
	mockHandler := handler.NewHandler(usecase)
	handlers := api.Handlers{
		Mhandler: mockHandler,
	}
	serverHTTP := api.NewServerHTTP(handlers)
	return serverHTTP, nil
}
